name: test

on: [ pull_request ]

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          cache: false
      - name: Lint Go Code
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: .
          args: --timeout=10m
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          cache: false
      - name: Test Go Code
        run: go test ./...